#!/bin/bash

###running tests.c (currently missing)
#make -C ../src
#gcc  -Wall -ansi -pedantic -g tests.c ../src/treeFuncs.c ../src/helper.c
#./a.out
#rm a.out

for file in $( ls inputFiles/* ); do
   echo -n "Testing with ${file} -- "
   \rm qa.db
   BASE=`basename ${file} .txt`

   # program testing
   ./../guess < ${file} > guessOutput/${BASE}.out 
   diff expected/${BASE}.db qa.db
   diff -w expected/${BASE}.out guessOutput/${BASE}.out
   if [ $? -eq 0 ]; then
      echo "Succeeded"
   else
      echo "Failed"
   fi
done
