#!/bin/bash


for file in $( ls testFiles/* ); do
   echo -n "Testing with ${file} -- "
   \rm ../qa.db
   BASE=`basename ${file} .txt`


   (../src; make)
   gcc  -Wall -ansi -pedantic -g tests.c ../src/treeFuncs.c ../src/helper.c
   ./a.out
   rm a.out

   # program testing
   ./../guess < ${file} > gout/${BASE}.out 
   diff expected/${BASE}.db qa.db
   diff -w expected/${BASE}.out gout/${BASE}.out
   if [ $? -eq 0 ]; then
      echo "Succeeded"
   else
      echo "Failed"
   fi
done
